##################################################################
#
#	Makefile for xxxx using gcc on Linux. 
#
#
#	Modified	by	Reason
# 	--------	--	------
#	10-Sep-10   CBL     Original
#
#####################################################################
# Machine specific stuff
#
#
LIBRARY = libOncore.a 
#
# Compile time resolution.
#
INCLUDE =  -I$(DRIVE)/common/utility
LIBS = 

# Rules to make the object files depend on the sources.
SRC     = 
SRCCPP  = Oncore.cpp

HEADERS = Oncore.hh

# When we build all, what do we build?
all:      $(LIBRARY)

include $(DRIVE)/common/makefiles/makefile.inc

